### PR TITLE
WIP: Changes from the upstream

### PR DESCRIPTION
**Pull request by armpogart**
See issue #55.

Incorporating changes from the upstream, still work in progress.

### CODE REVIEW

**Comment by samdark** [comment]
@armpogart is it ready to be merged?

**Comment by armpogart** [comment]
@samdark Still not, I will finish this PR this week, will let you know.

**Comment by SilverFire** [comment]
@armpogart do you have any progress on this?

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/jquery-pjax/commit/047a0b08c9eb4f23b9dfb3a5bdabdfd0d52e5917

**Pull request closed without merging**
